### ISSUE TITLE
Not a issue but a few words of appreciation from me!

### ISSUE THREAD

**Issue by loneicewolf** [mandiant/flare-floss#1026]
# Hi!

## __It's a thank you post!__

I just have to say thank you for making this, Why? Because it's rare people thank others when they use their software; if it's problems, one make issues, one **rarely actually type thanks** (at least, what I have seen)
so,

# Thanks for making this repo!
It is, very very useful. And it has helped me, A LOT. Thank you to all contributors; very much.  ❤️  

### Wishes & Saluting from Sweden!

I also always, **always** read this ([Github Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines)) to be sure I write good issues, (im trying to be open-minded and respectful, etc) (**even if this is just a thank you word!**)

Have a amazing week!

**Comment by loneicewolf** [comment]
This can be closed by the way! Since I don't want to take up space, But the Appreciation will always be there!

**Comment by mr-tz** [comment]
Thank you very much for the message :) You've already made my week!

**Comment by loneicewolf** [comment]
As I thought of closing this but, I guess it's always nice to hear that one is doing something good (something useful to others) I had to include Mandiant to my stuxnet repo as a "element of"  "thanks"  (at the `Acknowledgments section`)because it has been such a useful github project.


Now __ill not__ make more comments here, as I am **pretty sure you guys have lots to do**

good luck!

Will.
