### ISSUE TITLE
ERROR: floss: cannot deobfuscate strings from files larger than 0x1000000 bytes

### ISSUE THREAD

**Issue by Hamster4u** [mandiant/flare-floss#1035]
INFO: floss: extracting static strings
ERROR: floss: cannot deobfuscate strings from files larger than 0x1000000 bytes

**Comment by Hamster4u** [comment]
fixed with: floss.exe --large-file (here ur file .exe) > dump1.txt

**Comment by williballenthin** [comment]
as you've found @Hamster4u we require a special flag to analyze large files because it can be pretty slow, and want to keep you from making a mistake. thanks for documenting the fix here!
