### ISSUE TITLE
remove support for python 3.8

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#1052]
next min version: 3.9 or 3.10

**Comment by williballenthin** [comment]
discussion: https://github.com/mandiant/capa/issues/1966

**Comment by mr-tz** [comment]
FLOSS stats via https://pypistats.org/packages/flare-floss

Py 3.9 downloads 5-10% in the last 2 months.

![image](https://github.com/user-attachments/assets/09d4ed7c-393d-45a1-9db7-61212054b25a)
