### ISSUE TITLE
fail to emulate xmm instructions

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-floss#265]
sample: 64a38967b32c71575cd1da2b039a4a87

vivisect:
```
0x10002275: rep: movq mm0,qword [eax]
```

r2 (capstone):
```
0x10002275      f30f6f00       movdqu xmm0, xmmword [eax]
```

appears to be an issue with vivisect decoding the instruction incorrectly. because it sees `rep ...` the emulator gets stuck in a loop.

**Comment by mr-tz** [comment]
this has been fixed along the way
