### ISSUE TITLE
use function signatures to better recognize statically-linked routines

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-floss#285]
we can use vivisect's vamp subsystem for this.

reference here: https://gist.github.com/williballenthin/9bc18a0a8600caaf96e40e0623e97ce5

**Comment by williballenthin** [comment]
we'll need to come up with a signature database of common statically-linked functions.

one source might be from [retdec-support](https://github.com/avast-tl/retdec-support/releases). they have Yara rules to match known functions. we can convert these to vamp sigs. license is MIT.

**Comment by williballenthin** [comment]
retdec-support contains a lot of signatures:

![yara](https://user-images.githubusercontent.com/156560/38017767-40c54d24-3230-11e8-85e2-9bf6422447bf.PNG)

unfortunately, they're in [compiled form](https://yara.readthedocs.io/en/v3.4.0/commandline.html#running-yara-from-the-command-line). we'll have to decompile them somehow to recover the signature bytes, in order to translate to vamp. also, there's a lot of data there. i hope we can be efficient about it in memory.

**Comment by williballenthin** [comment]
keep an eye on https://github.com/avast-tl/retdec-support/issues/2

**Comment by williballenthin** [comment]
we can use FLIRT like how capa does this

**Comment by mr-tz** [comment]
this has been added via FLIRT
