### ISSUE TITLE
Stackstrings in allocated memory

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#286]
The malware with MD5 hash 1bb9e17cf5f76fdc04e780f15dd2c57e allocates memory and creates strings like so (0x40295B):
```
call    calloc
mov     dword ptr [eax], 'IRTS'
mov     dword ptr [eax+4], 'EHGN'
mov     esi, eax
mov     dword ptr [eax+8], '!ER'
```

**Comment by williballenthin** [comment]
how come this doesn't work? since we only look for stack strings on the stack?

**Comment by mr-tz** [comment]
Yes, most likely.

**Comment by mr-tz** [comment]
can't find the linked sample anymore 🙈  should work with hooked calloc now
