### ISSUE TITLE
String wrongly extracted

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-floss#316]
The output with floss is something like:

```
FLOSS extracted 4 stackstrings
ana.mth.com
ana.mtx.com
```

but when debugging the code in IDA, I observe that `ana.mth.com` is never in memory, but the following two strings:
```
ana.mtg.com
ana.mtx.com
```

note the `g` instead of the `h` in the first string.

This seems to me like a bug in FLOSS. I can't provide the file, but it was caused by something like the following assembly instructions (this is simplified, I hope I don't miss any important detail), where `var_2` is the variable which is a `g`, but FLOSS thinks it is an `h`:

```
mov     [ebp+var_1], 0
mov     eax, [ebp+var_1]
mov     cl, byte_407111[eax]
sub     cl, 1
mov     edx, [ebp+var_1]
mov     byte_407111[edx], cl
...
mov     al, byte_407111
mov     [ebp+var_2], al
```

Note the `sub      cl, 1`. It seems FLOSS is not taking it into account.

**Comment by mr-tz** [comment]
Good catch. For the stackstring emulation FLOSS iterates each instruction only once. The `sub` instruction occurs in a loop (and in another branch). I've seen other instances in malware where stackstrings are manipulated further before being used. If we increase the `maxhit` count (to let an instruction be emulated multiple times) FLOSS also extracts the modified string. We'll have to thing about how to handle this best.
