### ISSUE TITLE
Issues with floss

### ISSUE THREAD

**Issue by ytreister** [mandiant/flare-floss#327]
My first issue is that I can't use floss as a Python library because it is not in Python 3, this has forced me to use the Linux executable.  I understand that you need to wait for vivisect to update to Python 3.  Now my issues are as follows:
1. Can't read the file to be analyzed from stdin.  I am trying to call as python subprocess but I have the file contents in memory not in the filesystem
2. The -o option only allows me to have JSON printed to output file.  I would prefer if I could have an option like -j which would have JSON returned to stdout instead.

**Comment by williballenthin** [comment]
i would recommend using the `tempfile` package to handle the creation, use, and deletion of a temporary directory into which you can write the file to be analyzed and the results of the analysis.

alternatively, you could write a python2 script that interacts with the floss library as you describe, and integrate from there.

**Comment by mr-tz** [comment]
FLOSS supports Python 3 now. Does this fix your issue here?

**Comment by ytreister** [comment]
It fixes 1 of 3 issues.  It would be nice if floss would support supplying the file to be analyzed from STDIN (instead of from local file system) and if the JSON support would allow for the JSON to be returned to STDOUT instead of to a file on the local file system.

**Comment by mr-tz** [comment]
Gotcha, will address the other two as part of #328.

**Comment by mr-tz** [comment]
3. is handled now. If 2. is still an issue moving forward please open a new issue or even better a PR.
