### ISSUE TITLE
extract strings from go binaries

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-floss#370]
use logic from existing open source projects to parse the string table from programs compiled by the Go compiler.

"do what i mean"

**Comment by ramen0x3f** [comment]
Some examples: https://github.com/getCUJO/ThreatIntel/tree/master/Scripts/Ghidra

It would also be great to have some more advanced deobfuscation/emulation such as the degobfuscation Binary Ninja plugin from KryptosLogic: https://github.com/kryptoslogic/binja_degobfuscate

**Comment by berkaygunduzz** [comment]
Do you still want a passionate GSoC student for this task? I know Python very well and I would be appreciated for participation.

**Comment by williballenthin** [comment]
Of course, we’re reviewing proposals submitted by the deadline on Tuesday. Please see the further guidelines here:  https://github.com/mandiant/flare-gsoc-2023On Apr 2, 2023, at 5:00 PM, Berkay Gündüz ***@***.***> wrote:﻿
Do you still want a passionate GSoC student for this task? I know Python very well and I would be appreciated for participation.

**Comment by berkaygunduzz** [comment]
Do you have any personal suggestions for the proposal besides the guide? I would be happy if you give some tips, especially if it would make me more visible :)

**Comment by williballenthin** [comment]
I recommend starting with the guide, and then as we have a chance to interact over PR review and proposal feedback, we can get to know you more personally.

**Comment by berkaygunduzz** [comment]
Thank you very much!

**Comment by mr-tz** [comment]
closed via #792
