### ISSUE TITLE
Peridically _MEIxxxxxx folder is not removed which leads to /tmp growing in size

### ISSUE THREAD

**Issue by ytreister** [mandiant/flare-floss#433]
This is a bug with pyinstaller...
https://github.com/pyinstaller/pyinstaller/issues/2379

It seems like this bug will never be fixed, so it might make sense for floss to add some hack to workaround this issue.

**Comment by williballenthin** [comment]
the hack here is feasible: https://github.com/pyinstaller/pyinstaller/issues/2379#issuecomment-606631340

however, its a little scary: relying on permissions errors to detect when another pyinstaller program is running (and to not destroy their environment).
