### ISSUE TITLE
[Parrot OS] flare-floss throws errors while installing it via pip

### ISSUE THREAD

**Issue by CYB3RMX** [mandiant/flare-floss#457]
I tried to install it via pip with this command => ```pip3 install flare-floss``` and gives me this outputs:

![image](https://user-images.githubusercontent.com/42123683/139748131-71fba6a9-f351-4421-9a6a-d6c285e87abc.png)

It says this module needs ```vivisect==0.1.0``` but when i try to install it pip says there is no matcing distribution found for ```vivisect==0.1.0```.

**Comment by mr-tz** [comment]
There's currently no Python 3 release available. Sorry, the documentation is ahead and we hope to have a new release soon.
In the meantime you can follow the steps described at https://github.com/mandiant/flare-floss/blob/master/doc/installation.md#method-3-inspecting-the-floss-source-code.
