### ISSUE TITLE
Unable to detect two layers of obfuscation & Vivisect Error

### ISSUE THREAD

**Issue by alkeldi** [mandiant/flare-floss#463]
This [malware.zip](https://damctf-2021-prod-storage.storage.googleapis.com/uploads/f24e824c85f4c7470025601303d8bb3ae6d5fdb9ee6712d468561c719b9c3c0a/malware.zip) (password: `infected`) has two layers of obfuscation. First it uses XOR, then it does base64 encoding on the result. However, FLOSS is unable to decode the strings. 

When trying FLOSS with the **--function 0x140001000** argument, it encounters **ERROR:floss:Functions don't exist in vivisect workspace**.

**Comment by mr-tz** [comment]
Can you provide another link to the sample, again, please? Would love to triage this.

**Comment by mr-tz** [comment]
Please reopen when you can provide the sample again.
