### ISSUE TITLE
Use of eXpert flag

### ISSUE THREAD

**Issue by fear-the-reaper** [mandiant/flare-floss#511]
@williballenthin  I was trying to find what is the significance of the `-x`'s flag as the documentation states it `show duplicate offset/string combinations, save workspace, group function output`. However when running a test file from your test repository `test-decode-from-heap` it gave me the same JSON with or without the `-x` flag.

**Comment by williballenthin** [comment]
can you clarify if this is for a past release, like v1.7.0, or for the current master branch? we've been making some changes in this region recently and want to answer precisely.

**Comment by fear-the-reaper** [comment]
It is for a past release the latest one I think.

**Comment by williballenthin** [comment]
Ok thanks. 

Expert mode enables more verbose output that is probably most relevant to analysts willing to dig into the details and/or extend FLOSS. For example,

  - save the viv workspace to disk for faster subsequent performance,
  - show candidate decoding functions and their score, and
  - don’t try to deduplicate decoded strings.

These were primarily features we found useful during development but little demand for from users. Have they been useful to you? Can we tweak them in any way?

**Comment by williballenthin** [comment]
I’m not sure that this will affect the json output at all, though. Mostly just formatting the cli output.

**Comment by mr-tz** [comment]
As Willi said `-x` does not affect the JSON output, only the CLI output.

Moving forward the CLI will be largely revamped and this option won't be there to confuse people any more :)

**Comment by fear-the-reaper** [comment]
Ah, Thank you so much! I was racking my brain about this flag because I took the task to integrate the expert mode in that project's TIP. @williballenthin for me personally didn't have much use as we export our data to JSON so the CLI isn't a priority.
