### ISSUE TITLE
Add option to export static strings

### ISSUE THREAD

**Issue by orapic** [mandiant/flare-floss#514]
Hi,

Could there be an option to export the static strings that floss extracts?
When analyzing obfuscated strings that are not decoded in the first place by floss but are extracted as static after a dump with the decrypted strings, these static strings are not present in the `.json` output for x64dbg (at least that I know of, guess IDA is the same case).

I think it can be something that will not be used everytime but can be in certain situations. Having the option is always nice but not doing it by default is something expected.

**Comment by williballenthin** [comment]
Hi @orapic

Good idea, the static strings will definitely be present in the JSON output document in the upcoming v2.0 release. 

https://github.com/mandiant/flare-floss/blob/master/floss/results.py#L164
