### ISSUE TITLE
Document IDA and other tool script generation

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#558]
https://twitter.com/kienbigmummy/status/1539519016003588096

**Comment by symbolicvoid** [comment]
Could you please tell me what to do here? Do we want to add text to -H argument that tells users about these scripts in the scripts folder? Or do we want these scripts accessible from FLOSS itself using some arguments?

**Comment by williballenthin** [comment]
I think its sufficient to document the scripts in the github repository. i'd suggest the following:

  1. a section in the main readme describing that there are some additional scripts, and linking to the scripts directory, and
  2. a readme.md file in the scripts directory (which gets rendered by default when browsing in GH) that describes each of the scripts

Once we have some good text for these documentation sections, we can consider whether to add it to the `floss -h` output.

**Comment by symbolicvoid** [comment]
Can you assign me the issue then? I can write some docs for it, likely by today.
