### ISSUE TITLE
sigs does not exist or cannot be accessed

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#560]
Basic install with pip and I get the following error:

```
OSError: signatures path .../envs/py37/lib/python3.7/site-packages/floss/../sigs does not exist or cannot be accessed
```

See same issue in capa at https://github.com/mandiant/capa/issues/682

**Comment by rholloway** [comment]
👍  same issue. The standalone binaries have sigs functioning and no error but 2.0.0 on Pypi is missing sigs directory entirely in the package
