### ISSUE TITLE
How do you install this to IDA?

### ISSUE THREAD

**Issue by pseuxide** [mandiant/flare-floss#602]
Hi! 
I dont see the guide to install this to IDA as a plugin, so could you help me?
Putting `idaplugin.py` to plugin directory didnt work.
There is no info cuz its obvious for others?

**Comment by HongThatCong** [comment]
Run idaplugin.py as a Py script

**Comment by mr-tz** [comment]
Correct, thanks @HongThatCong! `idaplugin.py` is a IDAPython script you can just run within IDA (shortcut ALT + F7).

**Comment by pseuxide** [comment]
Oh, i tried that already...
I just run it again just in case and nothing happened visually. I dont think it added string annotation to disassembly view. 
I assumed some sort of window or string annotation would appear.
Only `Caching 'Imports'... ok` was displayed in output window btw.

my IDA is 7.7
and what i did is click File -> Script file -> select `idaplugin.py` which i copied from this repo. `pip flare-floss` has been done beforehand.
Plz tell me any step i missed here.

**Comment by mr-tz** [comment]
Hm, that should work and at least you should see more information in the Output window. Can you try again and copy the text from the Output window or a screenshot in here please?

**Comment by pseuxide** [comment]
I loaded up new exe into ida and test it.
absolutely nothing outputted.

https://user-images.githubusercontent.com/33578715/203870271-ffcc0f13-8431-41cf-994c-8576ce0b121a.mp4

**Comment by pseuxide** [comment]
I loaded up new exe into IDA and test it.
absolutely nothing came up.
Its 32 bit executable btw.

https://user-images.githubusercontent.com/33578715/203870405-0bbaeb28-60c8-433c-8542-b7574be9138f.mp4

p.

**Comment by pseuxide** [comment]
hold on, it worked somehow but running script directoly hold on ill post the video

**Comment by pseuxide** [comment]
Though its a bit bothering in comparison to run as a file, this way it runs nicely.
If you have no idea why 'run file' didnt work, its kinda fine for me.
https://user-images.githubusercontent.com/33578715/203876253-e6fb16ce-8f1b-4bcd-a1ae-8a0303867ef9.mp4

**Comment by mr-tz** [comment]
Ah there we go. When you save the file contents you copy pasted to a local file and run it, what happens?

**Comment by pseuxide** [comment]
The first video i posted was me literally running file.
Nothing happens. no output and no window created.

**Comment by mr-tz** [comment]
Have you tried to add `print` to see if the file and `main` execute properly?

**Comment by pseuxide** [comment]
It turned out that the `script file` button itself is not working, your script is fine.
Sorry for takin ur time. Thanks:)

**Comment by mr-tz** [comment]
😮 oh wow, glad we've figured it out 😄
