### ISSUE TITLE
networkx throw exception

### ISSUE THREAD

**Issue by HongThatCong** [mandiant/flare-floss#617]
In source file: \floss\floss\features\extract.py
Function def extract_function_loop(f)
Sometime bva variable is None, so networkx throw "None can not add as ...."
I temporarily fixed it as shown below

![image](https://user-images.githubusercontent.com/67528122/211684375-030519b0-cba2-41ec-aced-5271b39fba5d.png)

Please investigate and fix this error

**Comment by mr-tz** [comment]
Can you share an example binary to test with?

**Comment by HongThatCong** [comment]
Tks Moritz for reply
This attached file is a unpacked exe of a Themida protect sample
It can not run, but can analyze in IDA
[unpacked_HelpPane.exe.bin.gz](https://github.com/mandiant/flare-floss/files/10406974/unpacked_HelpPane.exe.bin.gz)

**Comment by mr-tz** [comment]
Oh, wow, sorry I didn't get a notification for your reply. I will take a look.
