### ISSUE TITLE
Floss cant solve the string protection

### ISSUE THREAD

**Issue by ReallReaper** [mandiant/flare-floss#634]
I have a program that is in .net, it is obfuscated with some things, one of them is mutation, flow control, but one of the most important is string protection, the program is a simple virus-free crack me.
I would like someone expert in reversing issues to get the string of this program, it does not download or execute any important file
File: https://gofile.io/d/htTyHK
virustotal: https://www.virustotal.com/gui/file/b06497b5985a273bb9aa9b866e922e46d57881251a2034bc0fded5a2309e2872?nocache=1

**Comment by mr-tz** [comment]
FLOSS doesn't do anything for .NET samples, unfortunately. I'd recommend using dnSpy to debug it and extract strings that way.
