### ISSUE TITLE
fix mypy code style violations

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#635]
so that we can merge https://github.com/mandiant/flare-floss/pull/632

**Comment by mr-tz** [comment]
Awesome, you got it!

**Comment by deepaksirohiwal** [comment]
How can I test locally before sending a pull request? Seems like the issue still persists.

**Comment by deepaksirohiwal** [comment]
I have sent a pull request. Please check if it resolves issue #632

**Comment by mr-tz** [comment]
Yes, thank you!
