### ISSUE TITLE
Add `--check-untyped-defs` to mypy and fix issues

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#645]
Warning in a recent CI run:
`By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]`.

Adding this improves type checking.

**Comment by deepaksirohiwal** [comment]
I want to work on this issue. 
Just wanted to know for which file, in particular, I have to check for this issue.
I have run this on /floss and have not found any `[annotation-unchecked]` warning.

**Comment by mr-tz** [comment]
This command with the added `--check-untyped-defs` should pass.

https://github.com/mandiant/flare-floss/blob/master/.github/workflows/tests.yml#L30

If there are no complains from mypy that's great :)

**Comment by deepaksirohiwal** [comment]
Getting an annotation error [here](https://github.com/mandiant/flare-floss/blob/d7399293bb51bd9c693d84c6c73e2decfee2fa17/floss/features/extract.py#L325) and need type annotation for "bb_handler"

**Comment by williballenthin** [comment]
yes, this flag enables more strict type checking, so it may raise additional issues that need to be fixed. addressing these issues may take a moderate amount of effort but be a substantial help. are you interested in taking this on @deepaksirohiwal? no pressure, just want to make clear what to expect.

**Comment by deepaksirohiwal** [comment]
yes, you can assign this issue to me

**Comment by mr-tz** [comment]
You got it, thanks!

**Comment by williballenthin** [comment]
closed in #647 thanks @deepaksirohiwal
