### ISSUE TITLE
Stack, Tight and Decoded strings do not render in color without -v

### ISSUE THREAD

**Issue by Shackles404** [mandiant/flare-floss#655]
Tight, Decoded and Stack strings seem to be left out of color formatting when rendered without verbose (-v) mode.
![image_2023-03-13_172602670](https://user-images.githubusercontent.com/126584775/224695024-1981cd7b-f538-4049-b396-66cf91ff5e91.png)
![image](https://user-images.githubusercontent.com/126584775/224695271-5f811c22-293d-485e-9534-bcb41a25085e.png)

They do work fine in -v mode though
![image_2023-03-13_172846752](https://user-images.githubusercontent.com/126584775/224695564-47a5801a-3529-4ba4-ab34-6ffaad645385.png)

Static strings render in color regardless.

Also, bit of an unrelated question, but why are the colors so bright for me?

**Comment by mr-tz** [comment]
I think it was the intention to only highlight strings in the verbose view to make them stand out.

In your screenshots I find the blue hard to read. We should address this. A solution for you would be to use a different terminal (vs. cmd.exe?). FLOSS output should be easily legible in all terminals/color settings though.

**Comment by Shackles404** [comment]
> I think it was the intention to only highlight strings in the verbose view to make them stand out.

In that case I think  we should also make the Static strings uncolored without -v mode since they're always colored.
![image_2023-03-14_140926737](https://user-images.githubusercontent.com/126584775/224943763-b061b7c0-e64d-4cbf-84ae-0ed3a782e4a6.png)



>In your screenshots I find the blue hard to read. We should address this. A solution for you would be to use a different terminal (vs. cmd.exe?). FLOSS output should be easily legible in all terminals/color settings though.
 
Yeah, unfortunately the colors seem to be too bright on windows command prompt, the blue is hard to read and the green is too bright for the eyes. This is probably the bigger issue here..

**Comment by mr-tz** [comment]
Good points. CC: @Arker123 who's looking more into this (ref: #623).

**Comment by williballenthin** [comment]
when students used capa in class this week via cmd.exe the blue text was *really* hard to read. i agree we should find a better combination of colors that ensures the output is still readable on cmd.exe.

**Comment by williballenthin** [comment]
we can't be the first to have this problem; so, what colors do popular CLI programs use?

**Comment by Shackles404** [comment]
@Arker123 Those colors look great! I like the cyan heading and green text personally.

> we can't be the first to have this problem; so, what colors do popular CLI programs use?

This is what [Rizin](https://github.com/rizinorg/rizin) uses:
![image_2023-03-15_114355908](https://user-images.githubusercontent.com/126584775/225222589-f4d5c6d2-7d67-403c-91d7-d49e8b2df87f.png)

These colors are much darker, I assume these ones are cyan for blue, dark green for green (and bit of lighter green sprinkled around, we could definitely use that to highlight something important too!) and olive for yellow. I am not sure if they would look bad on another terminal or light mode though..

**Comment by Shackles404** [comment]
I tried using `cyan` and though readable, it is still very bright on cmd. Plus `light_green` and `green` seem to be the same. Is it something about the library we are using? Even `cyan` and `light_cyan` are the same.
![image_2023-03-15_133538249](https://user-images.githubusercontent.com/126584775/225245691-ae5897b2-5059-4202-b239-74e997c3f27f.png)

**Comment by Shackles404** [comment]
![image_2023-03-15_133827718](https://user-images.githubusercontent.com/126584775/225246293-da2cf3ad-e6c6-4171-af06-c32dffa73fbd.png)

These are the colors available in termcolor, there does not seem to be a darker variant of these colours, unless `cyan` is darker version of `light_cyan`. Is it a problem because of cmd?

**Comment by mr-tz** [comment]
> Is it something with the command prompt being unable to render bold text?
Yeah, I can imagine especially cmd.exe having some limitations/issues compared to newer terminals.

**Comment by mr-tz** [comment]
> we can't be the first to have this problem; so, what colors do popular CLI programs use?

agreed, I was hoping there's a solid library or convention we can follow to make this work on black, dark, light, and white backgrounds...

**Comment by williballenthin** [comment]
closed in #659
