### ISSUE TITLE
gp: define database file format

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-floss#712]
want to be able to lookup from string to the number of times it's been seen in a representative dataset.

desirable fields:
  - global count
  - count among known malware
  - count among known goodware
  - section in file

**Comment by williballenthin** [comment]
propose starting with JSON because its easy for a human to inspect and explore. we can gzip the json file to keep the size small on disk. its up to floss to decode the entries in the file and index them as it needs.

initial proposal:

array of objects: `[ {...}, {...}, {...} ]`
each object has the keys:
  - string (string)
  - location (string): contains section name, or "overlay" or "header" or "gap"
  - global count (int)
  - known malware count (int)
  - known goodware count (int)

the counts are partitioned/aggregated by the (string, location) key.

like:

```json
{
  "string": "1.1.2",
  "location": ".rdata",
  "global count": 11121312412,
  "known malware count": 35325,
  "known goodware count": 89137819,
}
```

we could use msgspec to quickly decode the entries in the document: https://github.com/jcrist/msgspec

**Comment by williballenthin** [comment]
maybe we should use the jsonl format (rather than wrapping the list in `[]` then each line is implied to be a json object). this way we can easily concatenate the database files together.

**Comment by williballenthin** [comment]
proposing
https://github.com/mandiant/flare-floss/blob/4bdf5c93afdf5ebc36b9d30914fd6e6eeb3d0499/floss/qs/db/oss.py#L9-L35
and tests https://github.com/mandiant/flare-floss/blob/quantumstrand/tests/test_oss_db.py

in [4bdf5c9](https://github.com/mandiant/flare-floss/commit/4bdf5c93afdf5ebc36b9d30914fd6e6eeb3d0499)

ok @mr-tz ?

**Comment by mr-tz** [comment]
Should we track ASCII vs. UTF16LE type as well?

**Comment by williballenthin** [comment]
this may not be obvious at the source code level, so it may introduce some difficulty during extraction.

it sounds maybe nice to have. how would we use this information? to avoid string collisions? what else?

**Comment by mr-tz** [comment]
I'm torn on the `known goodware/malware count` wrt. to:
- updating the data
- confusing analysts: this string is more often seen in good/bad so the file is good/bad
- making it useful, e.g.
  - what are the base datasets?
  - would we ever update those?

The absolute numbers don't mean much IMO without a good explanation of the base data which would be hard to do.

Some of these aspects also apply to the general global count, but there we can have a hint like: `out of strings data from N binaries` (and don't have to qualify them into good/bad).

**Comment by williballenthin** [comment]
good arguments. lets remove this data until we have a great idea about how to collect it and explain it.

**Comment by williballenthin** [comment]
proposed database in:
https://github.com/mandiant/flare-floss/blob/2ccd4f8/floss/qs/db/gp.py
https://github.com/mandiant/flare-floss/blob/2ccd4f8/tests/test_gp_db.py

**Comment by mr-tz** [comment]
> ah, sorry, this is is for GP database, which makes this easy to extract. sure, lets capture this, too.

actually, for some databases the encoding may not be available, can we mark it optional (meaning implicit unknown) or make it explicit with types: ascii, utf16le, unknown?

**Comment by mr-tz** [comment]
sounds good

**Comment by mr-tz** [comment]
looking at this now, I think indexing just by string suffices. we can inspect encoding (if desired) in the indexed objects

**Comment by mr-tz** [comment]
updated in e8d80535b938f11841bdd8e89c887aa351aa5a48

also moved dbs to data directory in `floss/qs/db` in 1baeca0a7236036ad1abec64abb91810bf541f5a
