### ISSUE TITLE
consider using pyproject.toml instead of setup.py

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-floss#724]
https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

**Comment by Anu-Ra-g** [comment]
[project]
name = "flare-floss"
description = "FLARE Obfuscated String Solver"
readme = "README.md"
requires-python = ">=3.8"
license = {file="LICENSE"}
authors = [
    {name = "Willi Ballenthin", email = "william.ballenthin@mandiant.com"}, 
    {name = "Moritz Raabe", email = "moritz.raabe@mandiant.com"}
    ]
dynamic = ["version"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Topic :: Security",
]

dependencies = [
    "tabulate==0.9.0",
    "vivisect==1.1.1",
    "viv-utils[flirt]==0.7.9",
    "pydantic==1.10.9",
    "tqdm==4.65.0",
    "networkx==3.1",
    "halo==0.0.31",
    "rich==13.4.2",
    "pefile>=2022.5.30",
    "binary2strings==0.1.13",
]

[project.optional-dependencies]
dev = [
    "pre-commit==3.5.0", 
    "pyyaml==6.0.1", 
    "pytest==8.0.0", 
    "pytest-sugar==0.9.4", 
    "pytest-instafail==0.5.0", 
    "pytest-cov==4.1.0", 
    "pycodestyle==2.11.1", 
    "black==23.12.1", 
    "isort==5.13.2", 
    "mypy==1.8.0", 
    "types-PyYAML==6.0.10", 
    "types-tabulate==0.9.0.20240106",
    ]

[project.urls]
Source = "https://www.github.com/mandiant/flare-floss"
Issues = "https://github.com/mandiant/flare-floss/issues"
Documentation = "https://github.com/mandiant/flare-floss/blob/master/doc/usage.md"

[project.scripts]
floss = "floss.main:main"

[build-system]
requires = [
    "pyinstaller==6.3.0", 
    "setuptools==69.1.1", 
    "build==1.0.3"
    ]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "floss.version.__version__"}

[tool.setuptools.packages.find]
include = ["floss*"]

@williballenthin I made this pyproject.toml. The executable is working as expected. But on running this command 
`pre-commit run --all-files `, I'm failling in 57 tests
