### ISSUE TITLE
only load/match OSS database when a minimum threshold of hits are present

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-floss#746]
consider this example (PMA 03-02):
<img width="755" alt="image" src="https://github.com/mandiant/flare-floss/assets/156560/8b14a8af-6069-4340-ac2e-eb29ac1ef846">
a few strings are tagged cryptopp/openssl/liblzma, but they're false positives.

to address this, introduce a threshold, such as 3 or 5, number of matches to be present for the library to be displayed.

**Comment by mr-tz** [comment]
very nice idea!
