### ISSUE TITLE
Indicate strings in File Signature section

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#767]
This data currently shows up in overlay data.

**Comment by williballenthin** [comment]
pefile doesn't parse the authenticode signature today.

https://github.com/ralphje/signify looks like a good project to refer to. specifically:
https://github.com/ralphje/signify/blob/7a1b61446e53645b9725d690a83fa3d41d559137/signify/authenticode/signed_pe.py#L156-L192

the certificate table is referenced from data directory 5 and has a fairly simple structure that describes the ranges of the certificate structures. we could add these as additional ranges of the PE file and/or as structure hints.
