### ISSUE TITLE
Replace "\\n" with "\n"

### ISSUE THREAD

**Issue by HongThatCong** [mandiant/flare-floss#777]
1. https://github.com/mandiant/flare-floss/blob/037fc4b86ced148a0b4280ce3e8ced5e762315d1/scripts/idaplugin.py#L59
2. https://github.com/mandiant/flare-floss/blob/037fc4b86ced148a0b4280ce3e8ced5e762315d1/scripts/idaplugin.py#L100

Please replace "\\\\n" with "\n"
@williballenthin: I think it is better if floss result scan was showed in a Chooser.
I can pull request this chooser code.

**Comment by williballenthin** [comment]
that's great, thank you!
