### ISSUE TITLE
QS: show string encoding

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#780]
> Having UTF-16LE strings in the output by default is a great quality of life improvement. However, it would be nice if the output also indicated the string encoding that a particular string has.

via https://github.com/mandiant/flare-floss/issues/776

see https://github.com/getreu/stringsext for tool that already does this

**Comment by williballenthin** [comment]
i'll acknowledge that most tools today show the string encoding, so QS probably should too.

however, what is the value of this field, and is worth 6-8 characters per line to indicate the flavor? how does someone use this field? and, do they use the field in most invocations of strings/QS or just occasionally?

my feeling is that i rarely *use* this information, unless im crafting a yara rule or other signature that relies on the encoding. in this case, its certainly safer for me to use a hex editor, etc. to figure out the specific byte sequence. so, i wonder if it's a reasonable choice to *not* show the encoding in the common case?

thoughts @cxiao @mr-tz ?

**Comment by williballenthin** [comment]
alternatively, we could use color to indicate encoding; however, we should avoid using color as the *only* way to indicate something, so we'd still need some character/symbol to indicate the flavor.

we could a single character/emoji/unicode to indicate the flavor, rather than "#ascii" or whatever. this would save space and some visual noise. but, would it be easy enough to interpret?

**Comment by mr-tz** [comment]
I think a single character indication (A for ASCII, U for UTF-16LE, or A is default/implicit and U indicates a wide string) and maybe color would work well. With a dynamic UI we could also make this configurable.

**Comment by mr-tz** [comment]
One quick test, adding U for UTF16-LE strings and nothing for ASCII (assume default) before the offset:

<img width="1908" alt="WindowsTerminal_TLzXIJdPH0" src="https://github.com/mandiant/flare-floss/assets/17606537/09dc7a11-1519-483b-bf05-96ffc82dbd85">

**Comment by williballenthin** [comment]
> With a dynamic UI we could also make this configurable.

this is a good point, i won't get too hung up on this now.

> adding U for UTF16-LE strings and nothing for ASCII (assume default) before the offset

nice job. looks solid. only question is whether this is easy enough to interpret, which im inclined to believe, especially if we emit a footer with fields and recommended interpetation.

**Comment by mr-tz** [comment]
Explored to add a very basic and ugly header line. In general, I would prefer to move this to the documentation (a TLDR screenshot, for example) and to keep things as self-explanatory as much as possible.

<img width="566" alt="2023-06-07_11-41-24_WindowsTerminal" src="https://github.com/mandiant/flare-floss/assets/17606537/4174c690-6ac1-4941-956c-e1231815817e">

**Comment by mr-tz** [comment]
added in 8d41bde
