### ISSUE TITLE
use pathlib.Path to represent file system paths instead of strings

### ISSUE THREAD

**Issue by williballenthin** [mandiant/flare-floss#798]
throughout the codebase, replace string type variables with `pathlib.Path` type variables that represent file system paths. these objects have convenient methods/properties for common operations, as well as make clear how the data should be used (as a file system path, not a string to display to the user, or whatever).

**Comment by mr-tz** [comment]
Closing as complete. There may be a few outstanding instances which we can capture via `flake8-use-pathlib` (see #825).
Thanks, @DiegoRomeo!
