### ISSUE TITLE
PyPI Package

### ISSUE THREAD

**Issue by Py-Moon** [mandiant/flare-floss#824]
This tool it's fantastic, but it can be best Creating a Package with it

**Comment by mr-tz** [comment]
What do you mean?

**Comment by r0ny123** [comment]
> This tool it's fantastic, but it can be best Creating a Package with it

https://pypi.org/project/flare-floss/

**Comment by Py-Moon** [comment]
> What do you mean?

a Package with only the function, without Logger, parser etc..

`python
import floss

binary_string = B"\10x\"
decoded_string = floss.decode(binary_string)

`

**Comment by Py-Moon** [comment]
> > This tool it's fantastic, but it can be best Creating a Package with it
> 
> https://pypi.org/project/flare-floss/

this is another method to install del program, not the package

**Comment by williballenthin** [comment]
in your example above, what is `floss.decode`? 

as @r0ny123 mentions above, FLOSS is available via PyPI, so you can use it as a library once you've installed it like `pip install flare-floss`:

```
import floss.strings

for string in floss.strings.extract_ascii_strings(b"fdksla;fjkdsa;lfjksa;fjksa;fkjas;fkdjs;lafjk;askj;l"):
    print(string.string)
```
(or any other routine implemented/used by FLOSS).

**Comment by Py-Moon** [comment]
Thank you so much, i'm sorry for the confusion
