### ISSUE TITLE
Cannot deobfuscate large files

### ISSUE THREAD

**Issue by it4ch1-007** [mandiant/flare-floss#920]
![image](https://github.com/mandiant/flare-floss/assets/133276365/b64c5f0e-05b7-41b7-ae90-097826c66ab2)

 -  I got error when deobfuscating a large file for analysis.
 - It would be much better if floss would get me the strings till 0x1000000 bytes only, if not for the whole.

**Comment by mr-tz** [comment]
See https://github.com/mandiant/flare-floss/issues/893

**Comment by williballenthin** [comment]
> It would be much better if floss would get me the strings till 0x1000000 bytes only, if not for the whole.

FLOSS does a code and data analysis of the input program. If it truncated a large file, then many of the code/data references would be broken and this would have a major impact on the accuracy of FLOSS. Therefore, we prefer to use an all-or-nothing strategy.
