### ISSUE TITLE
QS: python-lancelot==0.8.8 ,most recent release not found on PyPi

### ISSUE THREAD

**Issue by ooprathamm** [mandiant/flare-floss#952]
Version issue results in error while installing [qs] requirements..

* setup.py
<img width="267" alt="image" src="https://github.com/mandiant/flare-floss/assets/89736193/860d533a-5253-4b12-a2cc-609c8cfa39fd">

*pip install error
<img width="809" alt="image" src="https://github.com/mandiant/flare-floss/assets/89736193/5f1db81a-e878-4b1b-af51-34ebe500710f">

*PyPi
<img width="852" alt="image" src="https://github.com/mandiant/flare-floss/assets/89736193/e334da04-2332-44df-b412-dd7024c871e6">

**Comment by williballenthin** [comment]
weird, the distribution seems to have succeeded here: https://github.com/williballenthin/lancelot/actions/runs/5394608322

I'll have to do a new release for 0.8.9. in the meantime, feel free to use 0.8.7.

**Comment by williballenthin** [comment]
https://github.com/williballenthin/lancelot/issues/197

**Comment by williballenthin** [comment]
v0.8.10 is now available on PyPI

https://pypi.org/project/python-lancelot/0.8.10/

**Comment by mr-tz** [comment]
closed via #963
