### ISSUE TITLE
pytest needs updates to replace deprecated functionality

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#957]
Needs some updates to replace deprecated functionality.

_Originally posted by @mr-tz in https://github.com/mandiant/flare-floss/issues/956#issuecomment-1979087661_

**Comment by SylanPadmakumar** [comment]
Hey, I would like to work on this. I just have to make changes to the conftest.py file if i am not wrong?

**Comment by mr-tz** [comment]
Go for it, yes, that should be it.

**Comment by Sylan-Padmakumar** [comment]
#959

**Comment by mr-tz** [comment]
Thank you!
