### ISSUE TITLE
update GitHub Actions

### ISSUE THREAD

**Issue by mr-tz** [mandiant/flare-floss#960]
similar to https://github.com/mandiant/capa/pull/2003

**Comment by riftsandroses** [comment]
Would love to work on this issue although will need more context on this.

**Comment by mr-tz** [comment]
Some Actions use outdated versions and can be updated similarly to what was done in the referenced PR in the capa repository.

**Comment by rimvydascivilis** [comment]
Hey @riftsandroses, I noticed that this issue is still unresolved. If for any reason you're unable or hesitant to tackle it, I'd be more than happy to take it.

**Comment by mr-tz** [comment]
I'd say go for it.

**Comment by riftsandroses** [comment]
Hi @rimvydascivilis please proceed with it. I am unable to find time to tackle this issue. Cheers!
