### ISSUE TITLE
python 3.12.1 failed to install floss

### ISSUE THREAD

**Issue by justtsuj** [mandiant/flare-floss#983]
`INFO: pip is looking at multiple versions of viv-utils[flirt] to determine which version is compatible with other requirements. This could take a while.`
`ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <3; 0.1.0rc1 Requires-Python <3; 0.1.0rc2 Requires-Python <3; 0.1.0rc3 Requires-Python <3; 0.2.0 Requires-Python <3; 0.2.1 Requires-Python`
`ERROR: Could not find a version that satisfies the requirement python-flirt==0.8.6; extra == "flirt" (from viv-utils[flirt]) (from versions: 0.8.9, 0.8.10)`
`ERROR: No matching distribution found for python-flirt==0.8.6; extra == "flirt"`

**Comment by Techno-Fox** [comment]
I'm getting the same error on my end as well.

command ran `pipx install flare-floss`

```
pip seemed to fail to build package:
    pydantic==1.9.1

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <3; 0.1.0rc1 Requires-Python <3; 0.1.0rc2 Requires-Python <3; 0.1.0rc3 Requires-Python <3; 0.2.0 Requires-Python <3; 0.2.1 Requires-Python <3
    ERROR: Could not find a version that satisfies the requirement python-flirt==0.7.0; extra == "flirt" (from viv-utils[flirt]) (from versions: 0.8.9, 0.8.10)
    ERROR: No matching distribution found for python-flirt==0.7.0; extra == "flirt"

Error installing flare-floss.
```

**Comment by mr-tz** [comment]
waiting on a new release of the dependency

**Comment by mr-tz** [comment]
viv-utils has been updated

**Comment by williballenthin** [comment]
FLOSS now works on Python 3.12 due to the dependency update:

![image](https://github.com/mandiant/flare-floss/assets/156560/7ed0e937-52c1-4140-bc09-10c629a1af0a)
